var albums = [{
        album: 1,
        id: 1,
        title: ' 1',
        url: 'https://via.placeholder.com/600/92c952',
        thumbnailUrl: 'https://via.placeholder.com/150/92c952',
    },
    {
        album: 1,
        id: 2,
        title: '2',
        url: 'https://via.placeholder.com/600/771796',
        thumbnailUrl: 'https://via.placeholder.com/150/771796',
    },
    {
        album: 1,
        id: 3,
        title: '3',
        url: 'https://via.placeholder.com/600/24f355',
        thumbnailUrl: 'https://via.placeholder.com/150/24f355',
    },
    {
        album: 1,
        id: 4,
        title: '4',
        url: 'https://via.placeholder.com/600/d32776',
        thumbnailUrl: 'https://via.placeholder.com/150/d32776',
    },
    {
        album: 1,
        id: 5,
        title: '5',
        url: 'https://via.placeholder.com/600/f66b97',
        thumbnailUrl: 'https://via.placeholder.com/150/f66b97',
    },
    {
        album: 1,
        id: 6,
        title: '6',
        url: 'https://via.placeholder.com/600/56a8c2',
        thumbnailUrl: 'https://via.placeholder.com/150/56a8c2',
    },
    {
        album: 1,
        id: 7,
        title: '7',
        url: 'https://via.placeholder.com/600/b0f7cc',
        thumbnailUrl: 'https://via.placeholder.com/150/b0f7cc',
    },
    {
        album: 1,
        id: 8,
        title: '8',
        url: 'https://via.placeholder.com/600/54176f',
        thumbnailUrl: 'https://via.placeholder.com/150/54176f',
    },
    {
        album: 1,
        id: 9,
        title: '9',
        url: 'https://via.placeholder.com/600/51aa97',
        thumbnailUrl: 'https://via.placeholder.com/150/51aa97',
    },
    {
        album: 1,
        id: 10,
        title: '10',
        url: 'https://via.placeholder.com/600/810b14',
        thumbnailUrl: 'https://via.placeholder.com/150/810b14',
    },
    {
        album: 1,
        id: 11,
        title: '11',
        url: 'https://via.placeholder.com/600/1ee8a4',
        thumbnailUrl: 'https://via.placeholder.com/150/1ee8a4',
    },
    {
        album: 1,
        id: 12,
        title: '12',
        url: 'https://via.placeholder.com/600/66b7d2',
        thumbnailUrl: 'https://via.placeholder.com/150/66b7d2',
    },
    {
        album: 1,
        id: 13,
        title: '13',
        url: 'https://via.placeholder.com/600/197d29',
        thumbnailUrl: 'https://via.placeholder.com/150/197d29',
    },
    {
        album: 1,
        id: 14,
        title: '14',
        url: 'https://via.placeholder.com/600/61a65',
        thumbnailUrl: 'https://via.placeholder.com/150/61a65',
    },
    {
        album: 1,
        id: 15,
        title: '15',
        url: 'https://via.placeholder.com/600/f9cee5',
        thumbnailUrl: 'https://via.placeholder.com/150/f9cee5',
    },
    {
        album: 1,
        id: 16,
        title: '16',
        url: 'https://via.placeholder.com/600/fdf73e',
        thumbnailUrl: 'https://via.placeholder.com/150/fdf73e',
    },
    {
        album: 1,
        id: 17,
        title: '17',
        url: 'https://via.placeholder.com/600/9c184f',
        thumbnailUrl: 'https://via.placeholder.com/150/9c184f',
    },
    {
        album: 1,
        id: 18,
        title: '18',
        url: 'https://via.placeholder.com/600/1fe46f',
        thumbnailUrl: 'https://via.placeholder.com/150/1fe46f',
    },
    {
        album: 1,
        id: 19,
        title: '19',
        url: 'https://via.placeholder.com/600/56acb2',
        thumbnailUrl: 'https://via.placeholder.com/150/56acb2',
    },
    {
        album: 1,
        id: 20,
        title: '20',
        url: 'https://via.placeholder.com/600/8985dc',
        thumbnailUrl: 'https://via.placeholder.com/150/8985dc',
    },
]